---
# tasks file for ngnixPlus

- name: Check /etc/ssl/nginx directory.
  stat:
    path: /etc/ssl/nginx
  register: my_folder

- name: "echo if directory already existed"
  debug:
    msg: "the /etc/ssl/nginx directory is already existed"
  when: my_folder.stat.exists

- name: "Create /etc/ssl/nginx directory if not exists"
  file:
    path: /etc/ssl/nginx
    state: directory
  when: my_folder.stat.exists == false

- name: Copy nginx-plus-repo to the /etc/ssl/nginx/
  copy:
    src: "{{item}}"
    dest: /etc/ssl/nginx/
    force: no
  with_items:
    - ~/ansible-code/roles/nginxPlus/files/cert/nginx-repo.crt
    - ~/ansible-code/roles/nginxPlus/files/cert/nginx-repo.key

- name: install ca-certificates dependency
  yum: name=ca-certificates state=present

- name: Download the nginx-plus-repo
  get_url:
    url: https://cs.nginx.com/static/files/nginx-plus-amazon2.repo
    dest: /etc/ssl/nginx/
    force: no

- name: check if nginx-plus-amazon2.repo exists
  stat:
    path: /etc/ssl/nginx/nginx-plus-amazon2.repo
  register: repo_exists

- name: Copy nginx-plus-repo to the /etc/ssl/nginx/
  copy:
    src: /etc/ssl/nginx/nginx-plus-amazon2.repo
    dest: /etc/yum.repos.d/
    remote_src: yes
    force: no

- name: install nginx-plus
  yum: name=nginx-plus state=present update_cache=yes

- name: enable the nginx service start at boot
  shell: systemctl enable nginx.service
  notify: restart nginx
