---
- name: Make sure we have a group_name group
  group:
    name: "{{ group_name }}"
    state: present

- name: Allow 'group_name group to have passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%steve"
    line: "%steve ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: "Create user accounts and add users to groups"
  user:
    name: "{{ item }}"
    groups: "steve"
  with_items: "{{ users }}"

- name: "Add authorized keys"
  authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', '/etc/ansible/'+ item + '.key.pub') }}"
  with_items: "{{ users }}"
  register: key

- name: debug
  debug:
      var: "{{ key }}"

- name: "Allow admin users to sudo without a password"
  lineinfile:
    dest: "/etc/sudoers" # path: in version 2.3
    state: "present"
    regexp: "^%admin"
    line: "%admin ALL=(ALL) NOPASSWD: ALL"