---
- name: Upgrade System
  apt: upgrade=dist update_cache=yes- name: Add certbot repository
  apt_repository:
   repo: 'ppa:certbot/certbot'
   
- name: Install Certbot
  apt:
   name: python-certbot
   state: present