---
- name: Set authorized key for remote user
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', '/etc/ansible/ssh/{{ item }}.pub') }}"
    with_items:
      - "{{ users }}"

- name: Disable password authentication for root
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin prohibit-password"