---
# Bring stack down
- hosts: loadbalancer
  become: true
  tasks:
    - service: name=haproxy state=stopped
    - wait_for: port=8080 state=drained

- hosts: webserver
  become: true
  tasks:
    - service: name=nginx state=stopped
    - wait_for: port=8080 state=stopped

# Bring stack up
- hosts: webserver
  become: true
  tasks:
    - service: name=nginx state=started
    - wait_for: port=8080

- hosts: loadbalancer
  become: true
  tasks:
    - service: name=haproxy state=started
    - wait_for: port=8080
